include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    
    # Disabled rules for prototyping
    prefer_const_constructors_in_immutables: false
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
