name: runhub
description: RunHub - Ultimate Sports Data Aggregation Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.2
  
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # File handling
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  
  # HTTP and networking
  http: ^1.1.0
  dio: ^5.3.2
  
  # Data parsing
  gpx: ^2.2.1
  xml: ^6.3.0
  
  # UI components
  flutter_map: ^6.0.1
  latlong2: ^0.9.1
  fl_chart: ^0.64.0
  
  # FFI Bridge (placeholder - will be configured with flutter_rust_bridge)
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

  # fonts:
    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto-Regular.ttf
    #     - asset: fonts/Roboto-Bold.ttf
    #       weight: 700